---
- name: Install a powerful BitTorrent client for KDE
  pacaur:
    name:
      - ktorrent
    state: present
  become: yes
  tags:
    - print_action

- name: Install the KTorrent plugins
  pacaur:
    name: '{{ KTORRENT_PLUGINS }}'
    state: present
  become: yes
  tags:
    - print_action

- name: Copy the KTorrent script to manage it from the command line
  copy:
    src: kt.sh
    dest: /usr/local/bin/kt
    mode: 0755
  become: yes
  tags:
    - print_action

- name: Create the KTorrent temporary files directory
  file:
    path: ~/.local/share/ktorrent
    state: directory
  changed_when: no

- name: Create the KTorrent downloads directory
  file:
    path: ~/Downloads/KTorrent
    state: directory
  tags:
    - print_action

- name: Push the KTorrent configuration file
  template:
    src: ktorrentrc.j2
    dest: ~/.config/ktorrentrc
    mode: 0600
  tags:
    - print_action

- name: Allow connections to the KTorrent ports
  community.general.ufw:
    name: KTorrent
    rule: allow
  become: yes
  notify:
    - reload firewall (non-system mode)
  when: UFW_ENABLED | default(True)
  tags:
    - print_action
    - ufw
