---
- name: Install pass packages
  pacaur:
    name: '{{ PASS_PACKAGES }}'
    state: present
  become: yes
  tags:
    - print_action

- name: Create a password store directory
  file:
    path: '~{{ PASSWORD_STORE_DIRECTORY }}'
    state: directory
  tags:
    - print_action

- name: Create a password store directory variable in the Bash shell profile file
  lineinfile:
    path: ~/.bash_profile
    regexp: '^#?\s*export\s+PASSWORD_STORE_DIR=(.*)$'
    line: 'export PASSWORD_STORE_DIR=~{{ PASSWORD_STORE_DIRECTORY }}'
    state: present
    create: yes
  when: >
    USER.SHELL is defined and
    USER.SHELL is search("/bin/bash")
  tags:
    - print_action

- name: Create a password store directory variable in the Zsh shell environment variables file
  lineinfile:
    path: ~/.zshenv
    regexp: '^#?\s*export\s+PASSWORD_STORE_DIR=(.*)$'
    line: 'export PASSWORD_STORE_DIR=~{{ PASSWORD_STORE_DIRECTORY }}'
    state: present
    create: yes
  when: >
    USER.SHELL is not defined or
    USER.SHELL is search("/bin/zsh")
  tags:
    - print_action

- include: qtpass.yml
  when: QTPASS_ENABLED | default(True)
