---
- name: Install Dragon Player
  pacaur:
    name:
      - dragon
    state: present
  become: yes
  tags:
    - print_action

- name: Map Dragon Player to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/dragon
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
