---
- name: Install KODI for Xorg
  pacaur:
    name:
      - kodi-x11
    state: present
  become: yes
  tags:
    - print_action

- name: Install KODI for Wayland
  pacaur:
    name:
      - kodi-wayland
    state: present
  become: yes
  when: KODI_WAYLAND_ENABLED | default(True)
  tags:
    - print_action

- name: Map KODI to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/kodi
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
