---
- name: Create the local share applications directory
  file:
    path: ~/.local/share/applications
    state: directory
  changed_when: no

- name: Copy the mpv desktop entry
  copy:
    src: mpv.desktop
    dest: ~/.local/share/applications/mpv.desktop
    mode: 0600
  tags:
    - print_action
