---
- name: Install youtube-dl packages
  pacaur:
    name:
      - ffmpeg
      - youtube-dl
    state: present
  become: yes
  tags:
    - print_action

- name: Create the youtube-dl resources directory
  file:
    path: ~/Videos/YouTube
    state: directory
  tags:
    - print_action

- name: Create the youtube-dl configuration directory
  file:
    path: ~/.config/youtube-dl
    state: directory
  changed_when: no

- name: Push the youtube-dl configuration file
  template:
    src: youtube.dl.j2
    dest: ~/.config/youtube-dl/config
  tags:
    - print_action

- name: Map youtube-dl to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/youtube-dl
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
