---
- name: restart ufw service
  service:
    name: ufw.service
    state: restarted
  tags:
    - print_action

- name: reload firewall
  community.general.ufw:
    state: reloaded
  when: UFW_ENABLED | default(True)
  tags:
    - print_action

- name: reload firewall (non-system mode)
  community.general.ufw:
    state: reloaded
  become: yes
  when: UFW_ENABLED | default(True)
  tags:
    - print_action
