---
- name: Install burning utilities
  pacaur:
    name: '{{ BURNING_UTILITIES }}'
    state: present
  tags:
    - print_action

- name: Install video and DVD ripper and encoder
  pacaur:
    name:
      - transcode
    state: present
  tags:
    - print_action

- name: Install DVD authoring tools
  pacaur:
    name:
      - dvdauthor
    state: present
  tags:
    - print_action

- name: Add user to the optical group
  user:
    name: '{{ USER.NAME }}'
    groups: optical
    append: yes
  tags:
    - print_action
    - user
