---
- name: Install Gwenview packages
  pacaur:
    name:
      - kimageformats
      - qt5-imageformats
      - gwenview
    state: present
  become: yes
  tags:
    - print_action

- name: Copy the Gwenview configuration file
  copy:
    src: gwenviewrc
    dest: ~/.config/gwenviewrc
    mode: 0600
  tags:
    - print_action

- name: Map Gwenview to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/gwenview
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
