---
- name: Install nomacs packages
  pacaur:
    name:
      - qt5-imageformats
      - nomacs
    state: present
  become: yes
  tags:
    - print_action

- name: Create the nomacs configuration directory
  file:
    path: ~/.config/nomacs
    state: directory
  changed_when: no

- name: Create the nomacs screenshots directory
  file:
    path: ~/Pictures/Screenshots
    state: directory
  changed_when: no

- name: Push the nomacs configuration file
  template:
    src: ImageLounge.conf.j2
    dest: '~/.config/nomacs/Image Lounge.conf'
  tags:
    - print_action

- name: Map nomacs to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/nomacs
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
