---
- name: Install qimgv packages
  pacaur:
    name:
      - qtraw
      - qimgv-light
    state: present
  tags:
    - print_action

- name: Install image format plugins for Qt5
  pacaur:
    name:
      - kimageformats
    state: present
  become: yes
  tags:
    - print_action

- name: Create the qimgv configuration directory
  file:
    path: ~/.config/qimgv
    state: directory
  changed_when: no

- name: Copy the qimgv configuration file
  copy:
    src: qimgv.conf
    dest: ~/.config/qimgv/qimgv.conf
  tags:
    - print_action

- name: Copy the qimgv Firejail profile
  copy:
    src: qimgv.profile
    dest: ~/.config/firejail/qimgv.profile
  notify:
    - activate user profiles
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail

- name: Map qimgv to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/qimgv
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
