---
- name: Install CD/DVD-ROM device emulator packages
  pacaur:
    name:
      - cdemu-daemon
      - cdemu-client
    state: present
  become: yes
  tags:
    - print_action

- name: Install a kernel module that emulates SCSI devices for custom kernels
  pacaur:
    name:
      - vhba-module-dkms
    state: present
  become: yes
  when: LTS_KERNEL
  tags:
    - print_action

- name: Install a simple CDEmu frontend for Plasma Desktop
  pacaur:
    name:
      - kde-cdemu-manager-kf5
    state: present
  when: PLASMA_DESKTOP_INSTALLED
  tags:
    - print_action

- name: Load fdrivers for CD/DVD drives
  command: modprobe sg sr_mod vhba
  ignore_errors: yes
  no_log: yes
  tags:
    - print_action

- name: Start and enable CDEmu daemon service
  service:
    name: cdemu-daemon.service
    state: started
    enabled: yes
  become: yes
  tags:
    - print_action
