---
- name: Install a kernel module that emulates SCSI devices
  pacaur:
    name:
      - vhba-module
    state: present
  become: yes
  when: not LTS_KERNEL
  tags:
    - print_action

- name: Install a kernel module that emulates SCSI devices for custom kernels
  pacaur:
    name:
      - linux-lts-headers
      - vhba-module-dkms
    state: present
  become: yes
  when: LTS_KERNEL
  tags:
    - print_action

- name: Install CD/DVD-ROM device emulator packages
  pacaur:
    name:
      - cdemu-daemon
      - cdemu-client
    state: present
  become: yes
  tags:
    - print_action

- name: Install a simple CDEmu frontend for Plasma Desktop
  pacaur:
    name:
      - kde-cdemu-manager-kf5
    state: present
  when: PLASMA_DESKTOP_INSTALLED
  tags:
    - print_action

- name: Enable CDEmu daemon service
  service:
    name: cdemu-daemon.service
    enabled: yes
  become: yes
  notify:
    - load fdrivers for CD/DVD drives
  tags:
    - print_action
