---
- name: alc applications playbook
  hosts: vm:desktop:portable:hp650:msigl63:msib85g43
  become: no
  roles:
    - { role: email-clients, tags: ['email-clients'] }
    - { role: instant-messaging-clients, tags: ['instant-messaging-clients'] }
    - { role: office, tags: ['office'] }
    - { role: file-manager, tags: ['file-manager'] }
    - { role: file-synchronization, tags: ['file-synchronization'] }
    - { role: image-viewers, tags: ['image-viewers'] }
    - { role: audio-players, tags: ['audio-players'] }
    - { role: video-players, tags: ['video-players'] }
    - { role: screen-capture, tags: ['screen-capture'] }
    - { role: graphics-editors, tags: ['graphics-editors'] }
    - { role: audio-video-editors, tags: ['audio-video-editors'] }
    - { role: disk-image-tools, tags: ['disk-image-tools'] }
    - { role: remote-desktop, tags: ['remote-desktop'] }
    - { role: tor, tags: ['tor'] }
    - { role: finalize, tags: ['finalize'] }
