---
- name: alc software development tools playbook
  hosts: vm:desktop:portable:msigl63:msib85g43
  become: no
  roles:
    - { role: vcs, tags: ['vcs'] }
    - { role: git-annex, tags: ['git-annex'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: electron, tags: ['electron'] }
    - { role: text-editors, tags: ['text-editors'] }
    - { role: python, tags: ['python'] }
    - { role: java, tags: ['java'] }
    - { role: android, tags: ['android'] }
    - { role: finalize, tags: ['finalize'] }
