---
- name: alc system playbook
  hosts: vm:desktop:portable:hp650:msigl63:msib85g43
  become: yes
  vars_prompt:
    - name: USER_PASSWORD
      prompt: user account password
      confirm: yes
  roles:
    - { role: repositories, tags: ['repositories'] }
    - { role: shell, tags: ['shell'] }
    - { role: bootloader, tags: ['bootloader'] }
    - { role: drives, tags: ['drives'] }
    - { role: hardware, tags: ['hardware'] }
    - { role: vm, tags: ['vm'], when: 'MACHINE_TYPE == "virtual"' }
    - { role: video, tags: ['video'], when: 'MACHINE_TYPE != "virtual"' }
    - { role: power-management, tags: ['power-management'] }
    - { role: finalize, tags: ['finalize'] }
