---
- name: alc system playbook
  hosts: vm:desktop:portable:hp650lts:msigl63:msib85g43lts
  become: yes
  vars_prompt:
    - name: USER_PASSWORD
      prompt: user account password
      confirm: yes
  roles:
    - { role: repositories, tags: ['repositories'] }
    - { role: shell, tags: ['shell'] }
    - { role: bootloader, tags: ['bootloader'] }
    - { role: finalize, tags: ['finalize'] }
