---
- name: Install discrete GPU drivers
  pacaur:
    name: '{{ DISCRETE_GPU_DRIVERS }}'
    state: present
  tags:
    - print_action

- name: Set the nvidia driver fact
  set_fact:
    DISCRETE_GPU_DRIVER_NAME: 'nvidia'
  changed_when: no
  when: ('"nvidia" in DISCRETE_GPU_DRIVERS') and not LTS_KERNEL

- name: Set the nvidia driver fact for the LTS kernel
  set_fact:
    DISCRETE_GPU_DRIVER_NAME: 'nvidia-lts'
  changed_when: no
  when: >
    DISCRETE_GPU_DRIVER_NAME is not defined and
    '"nvidia-lts" in DISCRETE_GPU_DRIVERS'

- name: Set the AMDGPU driver fact
  set_fact:
    DISCRETE_GPU_DRIVER_NAME: 'xf86-video-amdgpu'
  changed_when: no
  when: >
    DISCRETE_GPU_DRIVER_NAME is not defined and
    '"xf86-video-amdgpu" in DISCRETE_GPU_DRIVERS'

- name: Push the nvidia driver pacman hook
  template:
    src: nvidia.hook.j2
    dest: /etc/pacman.d/hooks/nvidia.hook
  when: >
    DISCRETE_GPU_DRIVER_NAME is defined and
    DISCRETE_GPU_DRIVER_NAME is search("nvidia")
  tags:
    - print_action

- include: bumblebee.yml
  when: >
    MACHINE_TYPE == 'portable' and
    EARLY_KMS_START is defined and
    DISCRETE_GPU_DRIVER_NAME is defined and
    DISCRETE_GPU_DRIVER_NAME is search("nvidia")

- name: Set the early KMS start fact for nvidia GPUs
  set_fact:
    EARLY_KMS_START: 'nvidia nvidia_modeset nvidia_uvm nvidia_drm'
  changed_when: no
  when: >
    EARLY_KMS_START is not defined and
    DISCRETE_GPU_DRIVER_NAME is defined and
    DISCRETE_GPU_DRIVER_NAME is search("nvidia")

- name: Set the early KMS start fact for AMD GPUs
  set_fact:
    EARLY_KMS_START: 'amdgpu'
  changed_when: no
  when: >
    EARLY_KMS_START is not defined and
    DISCRETE_GPU_DRIVER_NAME is defined and
    (DISCRETE_GPU_DRIVER_NAME == 'xf86-video-amdgpu')
