---
- name: Install a hackable text editor for the 21st Century
  pacaur:
    name:
      - atom
      - ctags
    state: present
  become: yes
  tags:
    - print_action

- name: Install Atom packages
  command: 'apm install {{ item }}'
  with_items: '{{ ATOM_PACKAGES }}'
  tags:
    - print_action

- name: Create the Atom configuration directory
  file:
    path: ~/.atom
    state: directory
  changed_when: no

- name: Push the Atom configuration file
  template:
    src: config.cson.j2
    dest: ~/.atom/config.cson
  tags:
    - print_action

- name: Map Atom to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/atom
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
