---
- include: code.yml
  when: VSCODE_VERSION == 'code'

- include: ms-vscode.yml
  when: VSCODE_VERSION == 'ms-vscode'

- include: vscodium.yml
  when: VSCODE_VERSION == 'vscodium'

- name: Install a library for passing menus over DBus
  pacaur:
    name:
      - libdbusmenu-glib
    state: present
  become: yes
  when: PLASMA_DESKTOP_INSTALLED
  tags:
    - print_action

- name: Install a debugger for Python used with Visual Studio and Visual Studio Code
  pacaur:
    name:
      - python-debugpy
    state: present
  when: PYTHON_DEBUGGER_ENABLED | default(True)
  tags:
    - print_action
