---
- name: Install the Android platform tools
  pacaur:
    name:
      - android-tools
    state: present
  become: yes
  tags:
    - print_action

- name: Install the official Android IDE
  pacaur:
    name:
      - android-studio
    state: present
  when: ANDROID_STUDIO_INCLUDED | default(True)
  tags:
    - print_action

- name: Install the Google Android SDK
  pacaur:
    name:
      - android-sdk
      - android-sdk-platform-tools
    state: present
  when: ANDROID_SDK_INCLUDED | default(False)
  tags:
    - print_action

- name: Install the Google Android Emulator
  pacaur:
    name:
      - android-emulator
    state: present
  when: ANDROID_EMULATOR_INCLUDED | default(False)
  tags:
    - print_action

- name: Install a 32-bit runtime libraries shipped by GCC
  pacaur:
    name:
      - lib32-gcc-libs
    state: present
  become: yes
  tags:
    - print_action

- name: Add user to the adbusers group
  user:
    name: '{{ USER.NAME }}'
    groups: adbusers
    append: yes
  become: yes
  tags:
    - print_action
    - user

- name: Create the Android SDK root directory environment variable in the Bash shell profile file
  lineinfile:
    path: ~/.bash_profile
    regexp: '^#?\s*export\s+ANDROID_SDK_ROOT=(.*)$'
    line: 'export ANDROID_SDK_ROOT={{ ANDROID_SDK_ROOT }}'
    state: present
    create: yes
  when: >
    USER.SHELL is defined and
    USER.SHELL is search("/bin/bash")
  tags:
    - print_action

- name: Create the Android SDK root directory environment variable in the Zsh shell environment variables file
  lineinfile:
    path: ~/.zshenv
    regexp: '^#?\s*export\s+ANDROID_SDK_ROOT=(.*)$'
    line: 'export ANDROID_SDK_ROOT={{ ANDROID_SDK_ROOT }}'
    state: present
    create: yes
  when: >
    USER.SHELL is not defined or
    USER.SHELL is search("/bin/zsh")
  tags:
    - print_action
