---
- name: Install Pandoc packages
  pacaur:
    name:
      - pandoc
      - pandoc-citeproc
      - pandoc-crossref
    state: present
  become: yes
  tags:
    - print_action

- name: Map Pandoc to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/pandoc
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
