---
- name: Download the overGrive package
  get_url:
    url: '{{ OVERGRIVE_PACKAGE_REPOSITORY_URL }}/{{ OVERGRIVE_PACKAGE_NAME }}'
    dest: ~/{{ OVERGRIVE_PACKAGE_NAME }}
    mode: 0644
  tags:
    - print_action

- name: Install overGrive dependencies
  pacaur:
    name: '{{ OVERGRIVE_DEPENDENCIES }}'
    state: present
  become: yes
  tags:
    - print_action

- name: Install a complete Google Drive desktop client solution for Linux
  pacaur:
    name:
      - /home/{{ USER.NAME }}/{{ OVERGRIVE_PACKAGE_NAME }}
    state: present
  become: yes
  tags:
    - print_action

- name: Remove the overGrive package
  file:
    path: /home/{{ USER.NAME }}/{{ OVERGRIVE_PACKAGE_NAME }}
    state: absent
    force: yes
  become: yes
  changed_when: no
