---
- name: Install an Open Source Continuous Replication / Cluster Synchronization Thing
  pacaur:
    name:
      - syncthing
    state: present
  become: yes
  tags:
    - print_action

- name: Allow connections to the Syncthing service ports
  community.general.ufw:
    name: syncthing
    rule: allow
  become: yes
  notify:
    - reload firewall (non-system mode)
  when: UFW_ENABLED | default(True)
  tags:
    - print_action
    - ufw

- name: Allow connections to the Syncthing Web GUI ports
  community.general.ufw:
    name: syncthing-gui
    rule: allow
  become: yes
  notify:
    - reload firewall (non-system mode)
  when: >
    (UFW_ENABLED | default(True)) and
    (SYNCTHING_WEB_GUI_EXTERNAL_ACCESS | default(False))
  tags:
    - print_action
    - ufw

- name: Install a GTK3 based GUI and notification area icon for Syncthing
  pacaur:
    name:
      - syncthing-gtk
    state: present
  become: yes
  when: SYNCTHING_GTK_GUI_ENABLED
  tags:
    - print_action

- include: syncthing-tray.yml
  when: >
    not SYNCTHING_GTK_GUI_ENABLED and
    (PACMAN_WRAPPER is not defined or (PACMAN_WRAPPER == 'yay'))

- name: Enable the Syncthing service
  systemd:
    name: syncthing.service
    state: started
    enabled: yes
    scope: user
  tags:
    - print_action
