---
- name: Install Kid3
  pacaur:
    name:
      - kid3
    state: present
  become: yes
  tags:
    - print_action

- name: Copy the Kid3 configuration file
  copy:
    src: kid3rc
    dest: ~/.config/kid3rc
    mode: 0600
  tags:
    - print_action

- name: Map Kid3 to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/kid3
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
