---
- name: Install Spotify
  pacaur:
    name:
      - spotify
    state: present
  tags:
    - print_action

- name: Create the Spotify configuration directory
  file:
    path: ~/.config/spotify
    state: directory
  changed_when: no

- name: Force the Spotify cache size limit
  lineinfile:
    path: ~/.config/spotify/prefs
    regexp: '^#?\s*storage\.size\s*=(.*)'
    line: 'storage.size={{ SPOTIFY_STORAGE_SIZE | default("4096") }}'
    state: present
    create: yes
  tags:
    - print_action

- name: Map Spotify to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/spotify
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
