---
- include: gnupg.yml

- include: openssh.yml

- name: Install FUSE client based on the SSH File Transfer Protocol
  pacaur:
    name:
      - sshfs
    state: present
  tags:
    - print_action

- include: ssh-agent.yml
  when: SSH_AGENT_ENABLED | default(True)

- name: Install mobile shell, surviving disconnects with local echo and line editing
  pacaur:
    name:
      - mosh
    state: present
  tags:
    - print_action

- name: Allow connections to the Mosh ports
  ufw:
    name: mosh
    rule: allow
  notify:
    - reload firewall
  when: UFW_ENABLED | default(True)
  tags:
    - print_action
    - ufw
