---
- name: Install a scalable distributed SCM tool
  pacaur:
    name:
      - mercurial
      - tk
    state: present
  become: yes
  tags:
    - print_action

- name: Push the Mercurial configuration file
  template:
    src: hgrc.j2
    dest: ~/.hgrc
  tags:
    - print_action
