---
- name: Install an application that helps you remember facts (like words/phrases in a foreign language) efficiently
  pacaur:
    name:
      - anki
    state: present
  become: yes
  tags:
    - print_action

- name: Map Anki to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/anki
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
