---
- name: Install an application that helps you remember facts (like words/phrases in a foreign language) efficiently
  pacaur:
    name:
      - anki
    state: present
  become: yes
  when: '"anki" in EDUCATION_TOOLS'
  tags:
    - print_action

- name: Install a Vocabulary Trainer
  pacaur:
    name:
      - parley
    state: present
  become: yes
  when: '"parley" in EDUCATION_TOOLS'
  tags:
    - print_action

- include: klavaro.yml
  when: '"klavaro" in EDUCATION_TOOLS'

- include: ktouch.yml
  when: '"ktouch" in EDUCATION_TOOLS'
