---
- name: Install a free touch typing tutor program
  pacaur:
    name:
      - klavaro
    state: present
  become: yes
  tags:
    - print_action

- name: Map Klavaro to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/klavaro
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
