---
- name: Install a Touch Typing Tutor
  pacaur:
    name:
      - ktouch
    state: present
  become: yes
  tags:
    - print_action

- name: Map KTouch to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/ktouch
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
