---
- name: Install a very powerful batch file renamer
  pacaur:
    name:
      - krename
    state: present
  become: yes
  tags:
    - print_action

- name: Install an advanced twin panel (commander style) file manager
  pacaur:
    name:
      - krusader
    state: present
  become: yes
  tags:
    - print_action

- name: Copy the Krusader configuration file
  copy:
    src: krusaderrc
    dest: ~/.config/krusaderrc
    mode: 0600
  tags:
    - print_action

- name: Create the Krusader local configuration directory
  file:
    path: ~/.local/share/krusader
    state: directory
  changed_when: no

# the Polish language only
- name: Copy the Krusader user actions file
  copy:
    src: useractions.xml
    dest: ~/.local/share/krusader/useractions.xml
    mode: 0644
  when: X_KEYBOARD_MAP is defined and (X_KEYBOARD_MAP == 'pl')
  tags:
    - print_action
