---
- name: Install a feature-rich screen recorder that supports X11 and OpenGL
  pacaur:
    name:
      - simplescreenrecorder
    state: present
  become: yes
  tags:
    - print_action

- name: Map SimpleScreenRecorder to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/simplescreenrecorder
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
