---
- name: Install Firefox packages
  pacaur:
    name: '{{ FIREFOX_PACKAGES }}'
    state: present
  become: yes
  tags:
    - print_action

- name: Map Firefox to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/firefox
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail

- name: Restrict Firefox access to /etc
  lineinfile:
    path: /etc/firejail/firefox.local
    regexp: '^#?\s*private-etc(.*)$'
    line: 'private-etc {{ VIRTUAL_ETC_ITEMS }}'
    state: present
    create: yes
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
