---
- name: Install an emulator with builtin DOS for running DOS Games
  pacaur:
    name:
      - dosbox
    state: present
  become: yes
  tags:
    - print_action

- name: Map DOSBox to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/dosbox
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
