---
- name: Install an anonymizing overlay network packages
  pacaur:
    name:
      - tor
      - torsocks
    state: present
  become: yes
  tags:
    - print_action

- name: Install an application to securely and easily download, verify, install, and launch Tor Browser in Linux
  pacaur:
    name:
      - torbrowser-launcher
    state: present
  become: yes
  when: TOR_BROWSER_LAUNCHER_ENABLED
  tags:
    - print_action

- name: Update the Tor configuration file to run its by the tor user
  lineinfile:
    path: /etc/tor/torrc
    regexp: '^#?User(.*)$'
    line: 'User tor'
    state: present
  become: yes
  tags:
    - print_action

- name: Map Tor to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/tor
    state: link
  become: yes
  when:  FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail

- name: Allow Tor access to /dev
  lineinfile:
    path: /etc/firejail/tor.local
    regexp: '^#?\s*ignore\s+private-dev$'
    line: 'ignore private-dev'
    state: present
    create: yes
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail

- name: Start and enable Tor service
  service:
    name: tor.service
    state: started
    enabled: yes
  become: yes
  when: TOR_SERVICE_ENABLED
  tags:
    - print_action
