---
- name: Install a free implementation of the Remote Desktop Protocol (RDP)
  pacaur:
    name:
      - freerdp
    state: present
  become: yes
  tags:
    - print_action

- name: Install Virtual Network Computing (VNC) server and client libraries
  pacaur:
    name:
      - libvncserver
      - libssh
    state: present
  become: yes
  tags:
    - print_action

- name: Install KDE Plasma Remote Desktop Client
  pacaur:
    name:
      - krdc
    state: present
  become: yes
  tags:
    - print_action
