---
- name: Install the X2Go server packages
  pacaur:
    name:
      - xorg-xauth
      - xorg-xhost
      - x2goserver
    state: present
  become: yes
  tags:
    - print_action

- include: x2go-desktop-sharing.yml
  when: X2GO_DESKTOP_SHARING_ENABLED | default(False)

- name: Enable X11 forwarding for the X2Go server
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding(.*)$'
    line: 'X11Forwarding yes'
    state: present
  become: yes
  notify:
    - restart SSH daemon service (non-system mode)
  tags:
    - print_action

- name: Allow TCP forwarding for the SSH connections
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowTcpForwarding(.*)$'
    line: 'AllowTcpForwarding yes'
    state: present
  become: yes
  notify:
    - restart SSH daemon service (non-system mode)
  tags:
    - print_action

- name: Enable using of localhost for the graphical interface
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11UseLocalhost(.*)$'
    line: 'X11UseLocalhost yes'
    state: present
  become: yes
  notify:
    - restart SSH daemon service (non-system mode)
  tags:
    - print_action

- name: Set the graphical interface display offset
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11DisplayOffset(.*)$'
    line: 'X11DisplayOffset 10'
    state: present
  become: yes
  notify:
    - restart SSH daemon service (non-system mode)
  tags:
    - print_action

- name: Initialize the X2Go server SQLite database
  command: 'x2godbadmin --createdb'
  become: yes
  tags:
    - print_action

- name: Create a symlink to publish the installed applications via the X2Go
  file:
    src: /usr/share/applications
    path: /etc/x2go/applications
    state: link
  become: yes
  tags:
    - print_action

- name: Create a symlink to allow launching Plasma Desktop via the X2Go
  file:
    src: /usr/bin/startplasma-x11
    path: /usr/bin/startkde
    state: link
  become: yes
  when: PLASMA_DESKTOP_INSTALLED
  tags:
    - print_action

- name: Start and enable X2Go server service
  service:
    name: x2goserver.service
    state: started
    enabled: yes
  become: yes
  tags:
    - print_action
