---
- name: Install an open-source software framework
  pacaur:
    name:
      - '{{ ELECTRON_VERSION }}'
    state: present
  become: yes
  tags:
    - print_action

- name: Install a simple extensive archive format for Electron
  pacaur:
    name:
      - asar
    state: present
  become: yes
  tags:
    - print_action
