---
- name: Create the Electron trash implementation variable in the Bash shell profile file
  lineinfile:
    path: ~/.bash_profile
    regexp: '^#?\s*export\s+ELECTRON_TRASH=(.*)$'
    line: 'export ELECTRON_TRASH={{ PLASMA_ELECTRON_TRASH }}'
    state: present
    create: yes
  when: >
    USER.SHELL is defined and
    USER.SHELL is search("/bin/bash")
  tags:
    - print_action

- name: Create the Electron trash implementation variable in the Zsh shell environment variables file
  lineinfile:
    path: ~/.zshenv
    regexp: '^#?\s*export\s+ELECTRON_TRASH=(.*)$'
    line: 'export ELECTRON_TRASH={{ PLASMA_ELECTRON_TRASH }}'
    state: present
    create: yes
  when: >
    USER.SHELL is not defined or
    USER.SHELL is search("/bin/zsh")
  tags:
    - print_action
