---
- name: Map nano editor to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/{{ item }}
    state: link
  become: yes
  with_items:
    - nano
    - rnano
  when: ("nano" in SHELL_PACKAGES) | default(False)
  tags:
    - print_action

- name: Map vim editor to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/{{ item }}
    state: link
  become: yes
  with_items:
    - rview
    - rvim
    - vim
    - vimdiff
    - vimtutor
    - xxd
  when: ("vim" in SHELL_PACKAGES) | default(False)
  tags:
    - print_action

- name: Map Ncdu analyzer to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/ncdu
    state: link
  become: yes
  when: ("ncdu" in SHELL_PACKAGES) | default(False)
  tags:
    - print_action

- name: Map GnuPG agent to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/gpg-agent
    state: link
  become: yes
  tags:
    - print_action

- name: Map OpenSSH agent to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/ssh-agent
    state: link
  become: yes
  tags:
    - print_action

- name: Map archiving utils to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/{{ item }}
    state: link
  become: yes
  with_items:
    - unzip
    - 7z
    - 7za
    - 7zr
    - unrar
    - atool
  tags:
    - print_action
