---
- name: Install a program that lets you manipulate digital audio waveforms
  pacaur:
    name:
      - audacity
    state: present
  become: yes
  tags:
    - print_action

- name: Map Audacity to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/audacity
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
