---
- name: Install a free and open-source video editor
  pacaur:
    name:
      - openshot
    state: present
  become: yes
  tags:
    - print_action

- name: Map OpenShot to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/openshot-qt
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
