---
- name: Install an editor for audio/video projects using the GStreamer framework
  pacaur:
    name:
      - pitivi
    state: present
  become: yes
  tags:
    - print_action

- name: Install the Pitivi plugins
  pacaur:
    name:
      - frei0r-plugins
      - gst-libav
    state: present
  become: yes
  tags:
    - print_action

- name: Map Pitivi to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/pitivi
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
