---
- name: Copy a default user avatar image
  copy:
    src: avatar.png
    dest: ~/.face
  tags:
    - print_action

- name: Create a symbolic link to the avatar
  file:
    src: ~/.face
    path: ~/.face.icon
    state: link
  tags:
    - print_action
