---
- name: Install darktable
  pacaur:
    name:
      - darktable
    state: present
  become: yes
  tags:
    - print_action

- name: Install the darktable plugins
  pacaur:
    name:
      - dcraw
      - imagemagick
    state: present
  become: yes
  tags:
    - print_action

- name: Map darktable to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/darktable
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
