---
- name: Install Krita
  pacaur:
    name:
      - krita
    state: present
  become: yes
  tags:
    - print_action

- name: Install the Krita plugins
  pacaur:
    name:
      - kimageformats
      - krita-plugin-gmic
    state: present
  become: yes
  tags:
    - print_action

- name: Map Krita to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/krita
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
