---
- name: Install Scribus
  pacaur:
    name:
      - scribus
    state: present
  become: yes
  tags:
    - print_action

- name: Map Scribus to Firejail
  file:
    src: /usr/bin/firejail
    path: /usr/local/bin/scribus
    state: link
  become: yes
  when: FIREJAIL_ENABLED | default(True)
  tags:
    - print_action
    - firejail
